stages:
  - build
  - deploy

.build:
  image: node:latest
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    untracked: true
    expire_in: 5 days
    paths:
      - dist

.deploy:
  stage: deploy
  before_script:
    - pip install awscli
  image: 'python:latest' # We use python because there is a well-working AWS Sdk
  script:
    - echo AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
    - echo AWS_REGION ${AWS_REGION}
    - echo BUCKET_NAME ${BUCKET_NAME}
    - aws s3 cp dist s3://${BUCKET_NAME}/public --recursive

pages: # the job must be named pages
  image: node:latest
  stage: deploy
  script:
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
    # optionally, you can activate gzip support wih the following line:
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  only:
    - master

build-dev:
  extends: .build
  variables:
    VUE_APP_GRAPHQL_HTTP: ${DEV_APP_GRAPHQL_HTTP}
    VUE_APP_APOLLO_API_KEY: ${DEV_APP_APOLLO_API_KEY}

deploy-dev:
  extends: .deploy
  environment:
    name: dev
    url: https://dev.love2sign4you.eu/
  variables:
    BUCKET_NAME: 'love2sign4you-dev-bucket'
    AWS_REGION: ${AWS_DEFAULT_REGION}
    AWS_ACCESS_KEY_ID: ${DEV_DEPLOY_AWS_ACCESS_KEY}
    AWS_SECRET_ACCESS_KEY: ${DEV_DEPLOY_AWS_SECRET_ACCESS_KEY}
